version: '3.8'

services:
    app:
        build: .
        env_file:
            - .env
        volumes:
            - /app/node_modules
            - ./src:/app/src
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - db
        restart: always
        networks:
            - hls
    db:
        image: postgres:13.5
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - postgres:/var/lib/postgresql/data
        restart: always
        networks:
            - hls

volumes:
    postgres:

networks:
    hls:
        name: ${NETWORK}
        driver: ${DRIVER}
