version: '3'

services:
    app:
        container_name: app
        image: dzehil02/nodejs2024q1-service-app-hls-dev
        env_file:
            - .env
        ports:
            - ${PORT}:${PORT}
        depends_on:
            - db
        restart: always
        networks:
            - hls
    db:
        container_name: db
        image: dzehil02/nodejs2024q1-service-db-hls-dev
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:${POSTGRES_PORT}
        volumes:
            - postgres_pub:/var/lib/postgresql/data
        restart: always
        networks:
            - hls

volumes:
    postgres_pub:

networks:
    hls:
        driver: ${DRIVER}
