version: '3.8'

services:
    app:
        build: .
        env_file:
            - .env
        volumes:
            - .:/app
            - /app/node_modules
        ports:
            - ${PORT}:4000
        command: npm start
        depends_on:
            - db
    db:
        image: postgres:13.5
        restart: always
        env_file:
            - .env
        ports:
            - ${POSTGRES_PORT}:5432
        volumes:
            - postgres:/var/lib/postgresql/data
volumes:
    postgres:
